### ISSUE TITLE
pyreportjasper or pyreport?

### ISSUE THREAD

**Issue by rafaelreuber** [jadsonbr/pyreportjasper#30]
This repository name is `pyreport` the but name of the project is `pyreportjasper`.
Why not change the repository name to pyreportjasper?

Yes, I know.. pyreport it's very good name. But the pip repository already have the project pyreport (owned by GaelVaroquaux) last released Jul 14, 2009.

Or.. even better, the project name could be `pyjasperstarter` in view of it is just a wrapper for the [jasperstarter](http://jasperstarter.cenote.de/)

**Comment by jadsonbr** [comment]
Thanks for the sugestion.
